# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Prashant Shrestha
description: >- # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
social:
  github:  intern0t
  bitbucket: intern0t
  gitlab: Scarecr0w
  linkedin: prashant-shrestha-368b5684
  email: contact@prashant.me
  disqus: prashantmshrestha
  twitter: InvalidxSyntax
ph: https://i.imgur.com/SnQUW1j.png

# Build settings
markdown: kramdown
kramdown:
 input: GFM
 auto_ids: true
 syntax_highlighter: rogue

plugins:
  - jekyll-feed
  - jekyll-paginate-v2

excerpt_separator: "<!--excerpt-->"

pagination:
  enabled: true
  debug: false
  collection: 'posts'
  per_page: 6
  permalink: '/page/:num/' # Pages are index.html inside this folder (default)
  title: ':title - page :num'
  limit: 0
  sort_field: 'date'
  sort_reverse: true
  category: 'posts'
  trail: 
    before: 2
    after: 2
############################################################

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
